# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1804.02"

  # VirtualBox
  config.vm.provider :virtualbox do |v|
    #v.customize ["modifyvm", :id, "--memory", "2048"]
    v.memory = 2048
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2220
    master.vm.provider :virtualbox do |v|
      v.name = "master"
    end
    config_synced_folder("master", master)
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.33.101"
    worker1.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2221
    worker1.vm.provider :virtualbox do |v|
      v.name = "worker1"
    end
    config_synced_folder("worker1", worker1)
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.33.102"
    worker2.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222
    worker2.vm.provider :virtualbox do |v|
      v.name = "worker2"
    end
    config_synced_folder("worker2", worker2)
  end

  # synced_folder for sharing demo scenario
  #   Installing sshfs fails on the proxy environment because
  #   it runs before configuring proxy settings in the provision
  #   Workaround is to defer enabling synced_folder until the privision is done
  #   on the proxy environment.
  #   This is a trick described in below:
  #    https://github.com/hashicorp/vagrant/issues/936#issuecomment-288063253
  #    https://stackoverflow.com/questions/24855635/check-if-vagrant-provisioning-has-been-done
  #
  #   NOTE: you need to run 'vagrant reload' once on the proxy environment
  def config_synced_folder(vm_name, config)
    if ENV['http_proxy'] and not File.exist?(".vagrant/machines/#{vm_name}/virtualbox/action_provision")
      # defer it if behind proxy and not provisioned yet
      return
    end
    config.vm.synced_folder "../", "/osc2018tk-demo", type: "sshfs"
  end

  # Provision
  # enable proxy during the provisioning
  if ENV['http_proxy']
    config.vm.provision "shell",
      inline: "echo 'export http_proxy=" + ENV['http_proxy'] + "' >>/etc/environment"
    config.vm.provision "shell",
      inline: "echo 'export https_proxy=" + ENV['https_proxy'] + "' >>/etc/environment"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.host_key_checking = false
    # at least one playbook needs to be run to generate ssh keys for ansible
    #ansible.playbook = "generate-inventory.yml"
    # for running demo scenario
    ansible.playbook = "demo-scenario.yml"
  end

end
