# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  # VirtualBox
  config.vm.provider :virtualbox do |v|
    #v.customize ["modifyvm", :id, "--memory", "2048"]
    v.memory = 2048
  end

  config.vm.define "master" do |master|
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.33.10"
    master.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2220
    master.vm.provider :virtualbox do |v|
      v.name = "master"
    end
  end

  config.vm.define "worker1" do |worker1|
    worker1.vm.hostname = "worker1"
    worker1.vm.network "private_network", ip: "192.168.33.101"
    worker1.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2221
    worker1.vm.provider :virtualbox do |v|
      v.name = "worker1"
    end
  end

  config.vm.define "worker2" do |worker2|
    worker2.vm.hostname = "worker2"
    worker2.vm.network "private_network", ip: "192.168.33.102"
    worker2.vm.network "forwarded_port", id: "ssh", guest: 22, host: 2222
    worker2.vm.provider :virtualbox do |v|
      v.name = "worker2"
    end
  end

  # Provision
  config.vm.provision "ansible" do |ansible|
    ansible.host_key_checking = false
    ansible.playbook = "generate-inventory.yml"
  end

end
